# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlantIot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlantIot
  pod 'AWSIoT'
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSDynamoDB', '~> 2.6.13'

end
