//
//  Example.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSCore

class Example: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userId: String?
    @objc var _highScore: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "plantiot-mobilehub-1242781300-Example"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_highScore" : "highScore",
        ]
    }
}
